#!/bin/bash

# Run unit tests automatically with a pre-commit hook.
# ---
# This file will be run by git on commit (name as pre-commit, no extension),
# and will finish the commit once the tests run successfully.
#
# (See https://blog.devgenius.io/automate-unit-tests-before-each-commit-by-git-hook-f331f0499786)

echo -e "Running javascript tests before commit . . .\n"

# Use -T because it's running inside a script, so don't attach extra terminal
docker-compose exec -T static_build lerna run test --stream

if [ $? -ne 0 ]; then
    echo "Tests must pass before commit. Please fix and commit again."

    exit 1 # Fail commit on non-zero exit code
fi
