name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
      # repo: https://github.com/actions/checkout
      # v2: https://github.com/actions/checkout/releases/tag/v2
    - name: Initial Checkout Setup
      uses: actions/checkout@v2
      # https://github.com/actions/setup-python
      # https://github.com/actions/setup-python/releases/tag/v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --force-reinstall pip-tools 'setuptools<58'
        pip-compile server/requirements.in --output-file server/requirements.txt
        pip-compile server/dev-requirements.in --output-file server/dev-requirements.txt
        pip-sync server/requirements.txt server/dev-requirements.txt
    - name: Run Tests
      run: |
        python server/manage.py test
